### ISSUE TITLE
Verify signature when saving a user discount

### ISSUE THREAD

**Issue by ricardobrg** [tiki/tiki-shopify#60]
As a developer
I need to verify the signature of the user discount to be saved in the backend
so that it prevents bad use of the endpoint

### What it is now
The endpoint for saving user discounts does not verify the signature.

### What it should be
The endpoint for saving user discounts verifies the signature and blocks not signed requests.

### Technical details 
There is an issue in TIKI SDK JS that prevents the signature to be verified.

Acceptance criteria
1. Non signed requests are blocked in user/discount endpoint

**Comment by mike-audi** [comment]
fixed in release sdk-js 2.1.4
